---
title: "p8105_hw2_xh2601"
author: "Samantha Xinwei Han"
date: "2025-09-29"
output: github_document
---

```{r setup, message = FALSE}
# load the tidyverse library
library(tidyverse)
```

## Problem 1

#### Step One. Clean the data in pols-month.csv
1. Use separate() to break up the variable mon into integer variables year, month, and day

```{r}
# create a dataframe named "pols" for pols-month.csv data
# use 'clean_names()' to clean variable names
# use 'separate()' to break "mon" variable into "year", "month", "day" variables, separated by "-"
# use 'mutate()' to convert character variables into integer variables
pols = 
  read_csv("fivethirtyeight_datasets/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day)
  )
```

2. Replace month number with month name

```{r}
# use 'mutate()' to replace month number with month name in "month"
pols = mutate(
  pols,
  month = case_match(
    month,
    1 ~ "January",
    2 ~ "February",
    3 ~ "March",
    4 ~ "April",
    5 ~ "May",
    6 ~ "June",
    7 ~ "July",
    8 ~ "August",
    9 ~ "September",
    10 ~ "October",
    11 ~ "November",
    12 ~ "December"
  )
)
```

3. Create a president variable taking values gop and dem, and remove prez_dem and prez_gop

```{r}
# use 'mutate()' to create "president" variable, so that if "prez_gop" is 1, "president" is "gop", and if "prez_dem" is 1, "president" is "dem"
# use 'select()' to remove "prez_dem" and "prez_gop"
# use 'select()' to reorder the dataframe, so that "president" is in the front
pols = pols |> 
  mutate(
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem"
    )
  ) |> 
  select(-prez_dem, -prez_gop) |> 
  select(year, month, day, president, everything())
```

4. Remove the day variable.




